paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags: 
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o por un fallo de conexión de la base de datos

  /api/products/{pid}:
    get:
      summary: Obtiene un solo producto a partir de su id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: id del producto que se desea obtener
        schema:
          $type: String
        responses:
          "200":
            description: Producto encontrado
            content:
              application/json:
                schema:
                  $ref: '#components/schemas/Product'
          "404":
            description: Producto no encontrado en la base de datos
    put:
      summary: Actualiza un producto a través de su id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: id del producto que se desea actualizar
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado por Mongo
        type: 
          type: String
          description: Describe la variedad del producto
        photo:
          type: String
          description: URL de la foto del producto
        category:
          type: String
          description: Corresponde al tipo de infusión (té o café)
        description:
          type: String
          description: Breve descripción del producto
        stock:
          type: Number
          description: "Cantidad en stock"
        code:
          type: String
          description: Código generado por el admin
        price:
          type: Number
          description: Precio asignado por el admin
        title:
          type: String
          description: Título del producto
      example:
        _id: ObjectId('64580cb57ef4b95d8efff162')
        type: Blend
        photo: https://www.modobarista.com/product_images/l/093/Catuai__98631_zoom.png
        category: cafe
        description: Un café muy especial
        stock: 197
        code: 004
        price: 2270
        title: Catuai
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: String
          description: Nombre o título del Producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Stock del producto
        category:
          type: String
          description: Categoría del producto
      example:
        title: Latte
        description: Tu latte ideal de cada mañana
        price: 43
        code: 010
        stock: 25
        category: cafe